export enum STYLECOLOR {
    l1 = 'var(--CLRl1)',
    l2 = 'var(--CLRl2)',
    l3 = 'var(--CLRl3)',
    l4 = 'var(--CLRl4)',
    l5 = 'var(--CLRl5)',
    l6 = 'var(--CLRl6)',
    l7 = 'var(--CLRl7)',
    l8 = 'var(--CLRl8)',
    t1 = 'var(--CLRt1)',
    t2 = 'var(--CLRt2)',
    t3 = 'var(--CLRt3)',
    t4 = 'var(--CLRt4)',
    t5 = 'var(--CLRt5)',
    t6 = 'var(--CLRt6)',
    t7 = 'var(--CLRt7)',
    t8 = 'var(--CLRt8)',
}
